---
id: tenki-api-2020
base_name: tenki-api-2020
tags: []
presentation_date: 2020/08/16
version: 2020.08.16
licenses: []
slideshare_id: livedoorapi
speaker_deck_id: livedoortian-qi-apizhong-liao-dui-ying
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
